Document that building from source requires pkg-config
When you build ligo.skymap from source but do not have pkg-config
installed, the setup.py script does not add the linker flags for
GSL. As a result, when you import ligo.skymap, you get this error:

```
ImportError: ...: undefined symbol: gsl_root_fdfsolver_steffenson
```

See
https://github.com/lpsinger/ligo.skymap/issues/3#issue-485301354.