Use artist.remove() instead of del
Matpotlib 3.7.0 raises this exception:

```
Traceback (most recent call last):
  File "/tmp/tmp.hoM8meeJAp/.tox/build_docs/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 481, in _run_code
    exec(code, ns)
  File "<string>", line 4, in <module>
  File "/tmp/tmp.hoM8meeJAp/.tox/build_docs/lib/python3.8/site-packages/ligo/skymap/tool/ligo_skymap_plot_airmass.py", line 127, in main
    del ax.lines[:]
TypeError: 'ArtistList' object does not support item deletion
```